version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80" 
    volumes:
      - type: bind
        source: ./frontend
        target: /app  

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # PHP-FPM
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
  #NGINX
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html 
    depends_on:
      - app

volumes:
  pgdata:
